#!/usr/bin/env python3

import argparse
import os
import re
from pathlib import Path
from datetime import datetime

import h5py
import matplotlib.pyplot as plt
import numpy as np


def date_from_ped_filename(filename):
    """
    Extract timestamp from filenames like:

        binary-Bruno-iog7-2026_07_09_12_19_49_CDT-packet.h5
        something-2026_07_09_12_19_49_CST-packet.h5

    Returns a datetime object if found, otherwise None.
    """

    basename = os.path.basename(filename)

    match = re.search(
        r'(\d{4}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2})_(CST|CDT)',
        basename
    )

    if match is None:
        print(f'Warning: could not find timestamp in filename: {basename}')
        return None

    date_str = match.group(1)
    return datetime.strptime(date_str, "%Y_%m_%d_%H_%M_%S")


def channel_tag(packet):
    """
    Convert a packet/channel record to the format expected by disable_single_channel.py:

        io_group-io_channel-chip_id-channel_id
    """

    return (
        f'{int(packet["io_group"])}-'
        f'{int(packet["io_channel"])}-'
        f'{int(packet["chip_id"])}-'
        f'{int(packet["channel_id"])}'
    )


def main(input_file, output_file, hot_pixel_list=None, n_hot_pixels=100):

    print('Opening file:', input_file)

    with h5py.File(input_file, 'r') as f:
        print('File opened.')

        if 'packets' not in f:
            raise KeyError('Could not find "packets" dataset in input file.')

        packets = f['packets']

        print('Selecting data packets...')
        mask = packets['packet_type'][:] == 0

        n_data_packets = np.count_nonzero(mask)

        if n_data_packets == 0:
            print('No data packets with packet_type == 0 found.')
            return

        timestamp = date_from_ped_filename(input_file)

        print('Counting the number of data packets per channel...')

        selected_packets = packets[mask]

        key, counts = np.unique(
            selected_packets[['io_group', 'io_channel', 'chip_id', 'channel_id']],
            return_counts=True
        )

    total = np.sum(counts)

    print('Sorting...')
    n_to_plot = min(n_hot_pixels, len(counts))

    # Hottest first
    sorting = np.argsort(counts)[-n_to_plot:][::-1]

    key = key[sorting]
    counts = counts[sorting]

    print('Sorted.')

    labels = [channel_tag(d).replace('-', ' - ') for d in key]
    tags = [channel_tag(d) for d in key]

    print()
    print(f'Top {n_to_plot} hot pixels:')
    print('io_group-io_channel-chip_id-channel_id : count : fraction')

    for tag, count in zip(tags, counts):
        fraction = count / max(total, 1)
        print(f'{tag} : {count} : {fraction:.3e}')

    if hot_pixel_list is not None:
        hot_pixel_path = Path(hot_pixel_list)
        hot_pixel_path.parent.mkdir(parents=True, exist_ok=True)

        with open(hot_pixel_path, 'w') as f:
            f.write('# Hot pixel list generated by analysis/plot_hot_pixels.py\n')
            f.write(f'# input_file: {input_file}\n')
            f.write(f'# total_data_packets: {total}\n')
            f.write('#\n')
            f.write('# Format:\n')
            f.write('# io_group-io_channel-chip_id-channel_id count fraction\n')
            f.write('#\n')

            for tag, count in zip(tags, counts):
                fraction = count / max(total, 1)
                f.write(f'{tag} {count} {fraction:.6e}\n')

        print()
        print('Saved hot pixel list to:', hot_pixel_path)

    plt.figure(figsize=(7, 16))

    fractions = counts / np.clip(total, 1, None)

    plt.barh(
        np.arange(len(counts)),
        fractions,
        tick_label=labels
    )

    # Put hottest channel at the top
    plt.gca().invert_yaxis()

    if timestamp is not None:
        title = timestamp.strftime('%Y/%m/%d %H:%M:%S')
    else:
        title = os.path.basename(input_file)

    plt.title(title)

    plt.xlabel('Fraction of data packets')
    plt.ylabel('io_group - io_channel - chip_id - channel')
    plt.xscale('log')

    plt.tight_layout()

    output_path = Path(output_file)

    if output_path.suffix == '':
        print('Warning: output file has no extension. Adding ".png".')
        output_path = output_path.with_suffix('.png')

    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.savefig(output_path)
    print()
    print('Saved plot to:', output_path)


if __name__ == '__main__':

    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--input_file',
        type=str,
        help='Path to packet-formatted HDF5 file',
        required=True
    )

    parser.add_argument(
        '--output_file',
        type=str,
        help='Output plot file, for example hot_pixels.png or hot_pixels.pdf',
        required=True
    )

    parser.add_argument(
        '--hot_pixel_list',
        type=str,
        default=None,
        help='Optional output txt file listing the hottest channels'
    )

    parser.add_argument(
        '--n_hot_pixels',
        type=int,
        default=100,
        help='Number of hottest channels to plot and optionally write to list'
    )

    args = parser.parse_args()

    main(**vars(args))
